### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Erudition** [lydell/elm-safe-virtual-dom#1]
This looks awesome, and like just what I need. My project currently uses [this patch](https://raw.githubusercontent.com/jinjor/elm-break-dom/master/patch/VirtualDom.patch) to handle dom inconsistencies caused by browser extensions, web components, and other tampering.
It looks like your project does a bit more!
However, I'm not sure how to use it. It kinda looks like this is a ready-to-publish npm package rather than mere patchfiles. I would love some README on how to take advantage of this code, as well as the benefits you added.

**Comment by lydell** [comment]
Yes, this will be written once the project is ready to be used.
